name: polaris_diffdock
channels:
  - pyg
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.16
  - pip
  - python-devtools
  # ProDy needs to be installed with conda
  - prody==2.2.0
  - scipy==1.12.0
